services:
  eshopservice:
    image: ${DOCKER_REGISTRY-}eshopservice
    depends_on:
      - db
      - redis
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: EShopService/Dockerfile
    #volumes:
     #- "C:/Users/lorda/NetCourse/EShopService:/app/data"

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    depends_on:
      - db
      - redis
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: UserService/Dockerfile
    #volumes:
     # - "C:/Users/lorda/NetCourse/UserService:/app/data"

  orderservice:
    image: ${DOCKER_REGISTRY-}ordersservice
    depends_on:
      - db
      - redis
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
     context: .
     dockerfile: OrdersService/Dockerfile
    ports:
        - "8060:8061"
    #volumes:
     # - "C:/Users/lorda/NetCourse/OrdersService:/app/data"
     
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

volumes:
  mssql_data: